### PR TITLE
Proposal for an event on genesis block day

### PR DESCRIPTION
**Pull request by nolim1t**
Proposal for an event on [genesis block](https://blockchair.com/bitcoin/block/00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048) day  (aka.  block 00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048).

Also marks bitcoin's 10th year anniversary too.

So think would be fun to take a trip up to Satoshi House

### CODE REVIEW

**Comment by meeDamian** [comment]
We should turn that into a big event.

**Comment by meeDamian** [comment]
I wanted to say, that we should consider celebrating on 10 years **of blocks**, but it seems that because of mining power growth we're quite ahead of schedule, and while 10 years of blocks would occur on block:

```
3652 * 24 * 6 = 525888
```

but we're already at `546807`, and it's still October 😅.

So I guess we need to stick to doing it calendar-based instead ;).

**Comment by meeDamian** [comment]
I wanted to say, that we should consider celebrating on 10 years **of blocks**, but it seems that because of mining power growth we're quite ahead of schedule, and while 10 years of blocks would occur on block:

```
3652 * 24 * 6 = 525888
```

but we're already at `546807`, and it's still October 😅.

So I guess we need to stick to doing it calendar-based instead ;).

**Comment by nolim1t** [comment]
I updated the date in the pull request.

Anyway suggestions for places. You can edit it directly in the branch of ideas as well.

**Comment by nolim1t** [comment]
I updated the date in the pull request.

Anyway suggestions for places. You can edit it directly in the branch of ideas as well.

**Comment by nolim1t** [comment]
I updated the date in the pull request.

Anyway suggestions for places. You can edit it directly in the branch of ideas as well.

**Comment by nolim1t** [comment]
I updated the date in the pull request.

Anyway suggestions for places. You can edit it directly in the branch of ideas as well.

**Comment by meeDamian** [comment]
LGTM.

Although we should consider making it a bigger event.

**Comment by meeDamian** [comment]
I'm trying to put together a bigger event, I'll keep ya all in loop.

**Comment by nolim1t** [comment]
Any ideas for genesis block day yet?

**Pull request closed without merging**
