### PR TITLE
3rd event proposal

### PR DESCRIPTION
**Pull request by meeDamian**
All previous events were on weekdays, and the 4th one is also on a weekday. Some people in the group were asking for a Weekend event, and 16th Sep is conveniently in-between the 2nd and 4th events. What do you guys think?

### CODE REVIEW

**Comment by AnotherDroog** [comment]
ACK

**Comment by topspin1** [comment]
The 17th is fine with me too.  I am flexible.

**Comment by AnotherDroog** [comment]
Thanks @topspin1 

I understand we want to have a meeting on a weekend, I just won't be able to attend that specific one

**Comment by meeDamian** [comment]
I'm ok with 17th as well

**Comment by meeDamian** [comment]
Changed to 17th. Any objections?

**Comment by topspin1** [comment]
Also Ok with the 17th

**Comment by meeDamian** [comment]
No objections, therefore a merge.

**Pull request merged**
